#!/bin/sh

# 04-install-lambda.sh
#
# Prepare system and install lambda.

. ./vind-config.sh
. ./vind-utils.sh

# env

unset CC CXX PREFIX DESTDIR HOST TOOLS
unset CPATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH

export MARKERS="/building/markers"
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/22/bin"
export CC=gcc
export CXX=g++
export CFLAGS="-I/usr/include"
export CPPFLAGS="-I/usr/include"
export LDFLAGS="-L/usr/lib"

mkdir -p "$MARKERS" || {
    error "Failed to create markers directory"
    exit 1
}

# resolv.conf

if [ ! -f "$MARKERS/.chroot_resolv_done" ]; then
    info "Configuring resolv.conf"

    cat > /etc/resolv.conf << 'EOF'
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

    if [ $? -ne 0 ]; then
        error "Failed to configure resolv.conf"
        exit 1
    fi

    touch "$MARKERS/.chroot_resolv_done" || {
        error "Failed to create resolv.conf marker"
        exit 1
    }
fi

# lambda install 


if [ ! -f "$MARKERS/.lambda_install_done" ]; then
    info "Installing lambda"

    cd /sources/lambda-manager || {
        error "Failed to enter /sources/lambda-manager"
        exit 1
    }

    ./installer.sh || exit 1 # no message bc lambda already has error messages on installer

    touch "$MARKERS/.lambda_install_done" || {
        error "Failed to create lambda install marker"
        exit 1
    }
fi

if [ ! -f "$MARKERS/.lambda_recipes_done" ]; then
    info "Configuring lambda package recipes"

    mkdir -p /usr/share/lambda/packages || {
        error "Failed to create lambda package directory"
        exit 1
    }

# lambda configuration

if [ ! -f "$MARKERS/.lambda_config_done" ]; then
    info "Configuring lambda"

    mkdir -p /etc/lambda || {
        error "Failed to create lambda configuration directory"
        exit 1
    }

    sed -i -e 's/^export CC="clang"$/export CC="gcc"/' -e 's/^export CXX="clang++"$/export CXX="g++"/' /etc/lambda/make.conf || {
        error "Failed to switch compiler to GCC"
        exit 1
    }

    cat > /etc/ld-musl-x86_64.path << 'EOF'
/lib
/usr/local/lib
/usr/lib
/usr/lib64
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create musl library path configuration"
        exit 1
    fi

    lambda mutate append llvm clang-config || {
        error "Failed to append clang-config and llvm to system"
    }

    touch "$MARKERS/.lambda_config_done" || {
        error "Failed to create lambda configuration marker"
        exit 1
    }
fi

# package recipes

if [ ! -f "$MARKERS/.lambda_recipes_done" ]; then
    info "Configuring lambda package recipes"

    mkdir -p /usr/share/lambda/packages || {
        error "Failed to create lambda package directory"
        exit 1
    }

    cat > /usr/share/lambda/packages/ninja.json << 'EOF'
{
  "name": "ninja",
  "description": "Small, fast build system designed to have build files generated by higher-level build systems such as Meson or CMake, focused on speed for incremental builds.",
  "version": "1.13.2",
  "dependencies": [],
  "download": [
    "curl -fL --retry 3 --retry-delay 2 -o ninja-1.13.2.tar.gz https://github.com/ninja-build/ninja/archive/refs/tags/v1.13.2.tar.gz",
    "tar -xf ninja-1.13.2.tar.gz"
  ],
  "build": [
    "cd ninja-1.13.2 && python3 configure.py --bootstrap"
  ],
  "install": [
    "install -Dm755 ninja-1.13.2/ninja \"$DESTDIR$PREFIX/bin/ninja\""
  ],
  "strip": [
    "find \"$DESTDIR$PREFIX\" -type f -exec sh -c 'file \"$1\" | grep -q \"ELF\" && strip --strip-unneeded \"$1\"' _ {} \\; 2>/dev/null || true"
  ]
}
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create ninja package recipe"
        exit 1
    fi

    cat > /usr/share/lambda/packages/cmake.json << 'EOF'
{
  "name": "cmake",
  "description": "A modern toolset used for generating Makefiles and other build systems.",
  "version": "4.2.3",
  "dependencies": [
    "curl",
    "libarchive",
    "libuv",
    "nghttp2"
  ],
  "download": [
    "curl -fL --retry 3 --retry-delay 2 -o cmake-4.2.3.tar.gz https://cmake.org/files/v4.2/cmake-4.2.3.tar.gz",
    "tar -xf cmake-4.2.3.tar.gz"
  ],
  "build": [
    "cd cmake-4.2.3 && sed -i '/\"lib64\"/s/64//' Modules/GNUInstallDirs.cmake",
    "cd cmake-4.2.3 && LD_LIBRARY_PATH=\"$PREFIX/lib\" CFLAGS=\"-pthread $CFLAGS\" CXXFLAGS=\"-pthread $CXXFLAGS\" LDFLAGS=\"-pthread $LDFLAGS\" ./bootstrap --prefix=\"$PREFIX\" --system-libs --mandir=/share/man --no-system-jsoncpp --no-system-cppdap --no-system-librhash --docdir=/share/doc/cmake-4.2.3",
    "cd cmake-4.2.3 && make $MAKEOPTS"
  ],
  "install": [
    "cd cmake-4.2.3 && make DESTDIR=\"$DESTDIR\" install"
  ],
  "strip": [
    "find \"$DESTDIR$PREFIX\" -type f -exec sh -c 'file \"$1\" | grep -q \"ELF\" && strip --strip-unneeded \"$1\"' _ {} \\; 2>/dev/null || true"
  ]
}
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create cmake package recipe"
        exit 1
    fi

    touch "$MARKERS/.lambda_recipes_done" || {
        error "Failed to create lambda recipes marker"
        exit 1
    }
fi

info "install lambda finished."
