#!/bin/sh

# 05-install-runtimes.sh.
#
# Patches some recipes and config files to install libc++, libc++abi, ninja and cmake

. ./vind-config.sh
. ./vind-utils.sh

export MARKERS="/building/markers"

mkdir -p "$MARKERS" || {
    error "Failed to create markers directory"
    exit 1
}

# lambda configuration

if [ ! -f "$MARKERS/.runtime_lambda_config_done" ]; then
    cat > /etc/lambda/make.conf <<'EOF'
# Lambda build environment

export CC="clang"
export CXX="clang++"

export CFLAGS="-O2 -pipe -march=alderlake"
export CXXFLAGS="${CFLAGS}"

# Library and pkg-config paths.
# Some packages, such as util-linux, may install libraries and their
# pkg-config files under /usr/lib64 on x86_64. Include both /usr/lib
# and /usr/lib64 so the linker and pkg-config can locate them during
# builds, regardless of which directory provides the required files.
export LDFLAGS="-Wl,-O1 -L/usr/lib -L/usr/lib64"
export LIBRARY_PATH="/usr/lib:/usr/lib64"
export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib64/pkgconfig"

export PREFIX="/usr"

export MAKEOPTS="-j6"

# Xorg-specific build environment (used by packages/xorg-libs and any
# X11-related package).

export XORG_PREFIX="${PREFIX}"
export XORG_CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static"
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create lambda make.conf"
        exit 1
    fi

    touch "$MARKERS/.runtime_lambda_config_done" || {
        error "Failed to create lambda configuration marker"
        exit 1
    }
fi

# install libc++ runtime

if [ ! -f "$MARKERS/.runtime_libcxx_done" ]; then
    lambda mutate append libc++ libc++abi || {
        error "Failed to append libc++ and libc++abi"
        exit 1
    }

    lambda reconcile || {
        error "Failed to reconcile libc++ and libc++abi"
        exit 1
    }

    touch "$MARKERS/.runtime_libcxx_done" || {
        error "Failed to create libc++ marker"
        exit 1
    }
fi

# remove bootstrap tools

if [ ! -f "$MARKERS/.runtime_bootstrap_purge_done" ]; then
    lambda mutate purge ninja cmake || {
        error "Failed to purge ninja and cmake"
        exit 1
    }

    lambda reconcile || {
        error "Failed to reconcile after purging ninja and cmake"
        exit 1
    }

    touch "$MARKERS/.runtime_bootstrap_purge_done" || {
        error "Failed to create bootstrap purge marker"
        exit 1
    }
fi

# package recipes

if [ ! -f "$MARKERS/.runtime_recipes_done" ]; then
    cat > /usr/share/lambda/packages/ninja.json <<'EOF'
{
  "name": "ninja",
  "description": "Small, fast build system designed to have build files generated by higher-level build systems such as Meson or CMake, focused on speed for incremental builds.",
  "version": "1.13.2",
  "dependencies": [],
  "download": [
    "curl -fL --retry 3 --retry-delay 2 -o ninja-1.13.2.tar.gz https://github.com/ninja-build/ninja/archive/refs/tags/v1.13.2.tar.gz",
    "tar -xf ninja-1.13.2.tar.gz"
  ],
  "build": [
    "cd ninja-1.13.2 && CXX=\"$CXX\" CXXFLAGS=\"$CXXFLAGS -stdlib=libc++\" LDFLAGS=\"$LDFLAGS -stdlib=libc++\" python3 configure.py --bootstrap"
  ],
  "install": [
    "install -Dm755 ninja-1.13.2/ninja \"$DESTDIR$PREFIX/bin/ninja\""
  ],
  "strip": [
    "find \"$DESTDIR$PREFIX\" -type f -exec sh -c 'file \"$1\" | grep -q \"ELF\" && strip --strip-unneeded \"$1\"' _ {} \\; 2>/dev/null || true"
  ]
}
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create ninja package recipe"
        exit 1
    fi

    cat > /usr/share/lambda/packages/cmake.json <<'EOF'
{
  "name": "cmake",
  "description": "A modern toolset used for generating Makefiles and other build systems.",
  "version": "4.2.3",
  "dependencies": [
    "curl",
    "libarchive",
    "libuv",
    "nghttp2"
  ],
  "download": [
    "curl -fL --retry 3 --retry-delay 2 -o cmake-4.2.3.tar.gz https://cmake.org/files/v4.2/cmake-4.2.3.tar.gz",
    "tar -xf cmake-4.2.3.tar.gz"
  ],
  "build": [
    "cd cmake-4.2.3 && sed -i '/\"lib64\"/s/64//' Modules/GNUInstallDirs.cmake",
    "cd cmake-4.2.3 && LD_LIBRARY_PATH=\"$PREFIX/lib\" CC=\"$CC\" CXX=\"$CXX\" CFLAGS=\"-pthread $CFLAGS\" CXXFLAGS=\"-pthread -stdlib=libc++ $CXXFLAGS\" LDFLAGS=\"-stdlib=libc++ $LDFLAGS\" ./bootstrap --prefix=\"$PREFIX\" --system-libs --mandir=/share/man --no-system-jsoncpp --no-system-cppdap --no-system-librhash --docdir=/share/doc/cmake-4.2.3",
    "cd cmake-4.2.3 && make $MAKEOPTS"
  ],
  "install": [
    "cd cmake-4.2.3 && make DESTDIR=\"$DESTDIR\" install"
  ],
  "strip": [
    "find \"$DESTDIR$PREFIX\" -type f -exec sh -c 'file \"$1\" | grep -q \"ELF\" && strip --strip-unneeded \"$1\"' _ {} \\; 2>/dev/null || true"
  ]
}
EOF

    if [ $? -ne 0 ]; then
        error "Failed to create cmake package recipe"
        exit 1
    fi

    touch "$MARKERS/.runtime_recipes_done" || {
        error "Failed to create runtime recipes marker"
        exit 1
    }
fi

# install build tools

if [ ! -f "$MARKERS/.runtime_tools_done" ]; then
    lambda mutate append cmake ninja || {
        error "Failed to append cmake and ninja"
        exit 1
    }

    lambda reconcile || {
        error "Failed to reconcile cmake and ninja"
        exit 1
    }

    touch "$MARKERS/.runtime_tools_done" || {
        error "Failed to create runtime tools marker"
        exit 1
    }
fi

info "install runtimes finished."
